ErrorDocument 403 /custom/mjlfinancement/nativeforbidden.php

<LocationMatch "^/(accountancy|adherents|ai|api|asset|asterisk|banque|barcode|blockedlog|bom|bookcal|bookmarks|categories|collab|comm|commande|compta|contact|contrat|cron|datapolicy|dav|delivery|don|ecm|emailcollector|eventorganization|expedition|expensereport|exports|fichinter|fourn|ftp|holiday|hrm|imports|install|intracommreport|knowledgemanagement|loan|mailmanspip|margin|modulebuilder|mrp|multicurrency|opensurvey|partnership|paybox|paypal|printing|product|projet|reception|recruitment|resource|salaries|societe|stripe|subtotals|supplier_proposal|takepos|tax|ticket|variants|webhook|webportal|website|webservices|workstation|zapier)(/|$)">
	Require all denied
</LocationMatch>

<Location "/core/tools.php">
	Require all denied
</Location>

<LocationMatch "^/admin(/|$)">
	Require all denied
</LocationMatch>

<LocationMatch "^/user/(?!logout\.php$|passwordforgotten\.php(?:$|\?))">
	Require all denied
</LocationMatch>
