<?php

require_once DOL_DOCUMENT_ROOT.'/custom/mjlfinancement/lib/mjl_activity_access.lib.php';
require_once DOL_DOCUMENT_ROOT.'/custom/mjlfinancement/lib/mjl_form_submission.lib.php';
require_once DOL_DOCUMENT_ROOT.'/custom/mjlfinancement/lib/mjl_navigation.lib.php';
require_once DOL_DOCUMENT_ROOT.'/custom/mjlfinancement/lib/mjl_page_header.lib.php';
require_once DOL_DOCUMENT_ROOT.'/custom/mjlfinancement/class/mjlactivitycommand.class.php';

function mjl_request_forbidden(){http_response_code(403);header('Content-Type: text/plain; charset=UTF-8');print 'Forbidden';exit;}
function mjl_request_bad(){http_response_code(400);header('Content-Type: text/plain; charset=UTF-8');print 'Requête non valide';exit;}
function mjl_request_decimal($name,array $source){if(!isset($source[$name])||!is_scalar($source[$name]))return '';$value=(string)$source[$name];return preg_match('/^[1-9][0-9]*$/',$value)===1&&strlen($value)<=19&&(strlen($value)<19||strcmp($value,'9223372036854775807')<=0)?$value:'';}
function mjl_request_status_label($status){$labels=array('PENDING'=>'En attente','APPROVED'=>'Approuvée','REJECTED'=>'Rejetée','WITHDRAWN'=>'Retirée');return $labels[$status]??'Statut inconnu';}
function mjl_request_unavailable(){global $user;http_response_code(503);llxHeader('','Demandes d’exception');mjl_navigation_shell_start($user);print '<div class="mjl-workspace">'.mjl_page_header_render('Demandes d’exception').'<section class="mjl-workspace-section">'.mjl_ui_system_state('unavailable','Demandes indisponibles','Le service ne peut pas charger les demandes pour le moment. Réessayez plus tard.').'</section></div>';mjl_navigation_shell_end();llxFooter();}
function mjl_request_context($action,$type,$id,$version){global $conf,$user;return array('user_id'=>(int)$user->id,'entity'=>(int)$conf->entity,'route'=>'operationrequests','form'=>$type,'action'=>$action,'object_id'=>(int)$id,'version'=>(int)$version);}
function mjl_request_hidden($action,$type,$id,$version){return '<input type="hidden" name="token" value="'.dol_escape_htmltag(newToken()).'"><input type="hidden" name="mjl_submission" value="'.dol_escape_htmltag(mjl_form_submission_issue(mjl_request_context($action,$type,$id,$version))).'"><input type="hidden" name="action" value="'.$action.'"><input type="hidden" name="request_type" value="'.$type.'"><input type="hidden" name="request_id" value="'.(int)$id.'"><input type="hidden" name="version" value="'.(int)$version.'">';}

function mjl_operation_request_route()
{
	global $db,$conf,$user;$method=strtoupper((string)($_SERVER['REQUEST_METHOD']??'GET'));if(empty($user->id)||!mjl_activity_access_can_enter_list($user)||!in_array($method,array('GET','POST'),true))mjl_request_forbidden();try{mjl_rst006b_require_target($db);}catch(Throwable $exception){mjl_request_unavailable();return;}
	if($method==='POST')mjl_request_post();
	require_once __DIR__.'/mjl_monitoring_access.lib.php';
	if (mjl_monitoring_readiness()!==0) { require_once __DIR__.'/mjl_monitoring_route.lib.php'; mjl_monitoring_page('requests'); return; }
	foreach(array_keys($_GET)as$key)if(!in_array($key,array('type','status','page','result'),true))mjl_request_forbidden();
	$type=isset($_GET['type'])&&is_scalar($_GET['type'])?(string)$_GET['type']:'';$status=isset($_GET['status'])&&is_scalar($_GET['status'])?(string)$_GET['status']:'PENDING';if(!in_array($type,array('','CANCELLATION','REOPENING'),true)||!in_array($status,array('','PENDING','APPROVED','REJECTED','WITHDRAWN'),true))mjl_request_bad();$page=1;if(isset($_GET['page'])){$page=(int)mjl_request_decimal('page',$_GET);if($page<1||$page>intdiv(PHP_INT_MAX,50))mjl_request_bad();}$offset=($page-1)*50;$queries=array();$assignment=mjl_scope_is_input_agent($user)?' INNER JOIN '.$db->prefix().'mjlfinancement_activity_assignment aa ON aa.entity=r.entity AND aa.fk_activity=r.fk_activity AND aa.fk_user='.(int)$user->id.' AND aa.date_end IS NULL':'';$where=' WHERE r.entity='.(int)$conf->entity.($status!==''?" AND r.status='".$db->escape($status)."'":'');
	if($type===''||$type==='CANCELLATION')$queries[]="SELECT 'CANCELLATION' AS request_type,r.rowid,r.target_version,CASE WHEN r.target_type='ACTIVITY' THEN a.version ELSE o.version END AS current_target_version,r.fk_requester,r.requester_name_snapshot,r.reason,r.status,r.version,r.date_request,CASE WHEN r.target_type='ACTIVITY' THEN a.ref ELSE CONCAT(a.ref,' / ',o.name) END AS target_label FROM ".$db->prefix().'mjlfinancement_cancellation_request r INNER JOIN '.$db->prefix().'mjlfinancement_activity a ON a.entity=r.entity AND a.rowid=r.fk_activity LEFT JOIN '.$db->prefix()."mjlfinancement_operation o ON r.target_type='OPERATION' AND o.entity=r.entity AND o.rowid=r.target_id".$assignment.$where;
	if($type===''||$type==='REOPENING')$queries[]="SELECT 'REOPENING' AS request_type,r.rowid,r.target_version,o.version AS current_target_version,r.fk_requester,r.requester_name_snapshot,r.reason,r.status,r.version,r.date_request,CONCAT(a.ref,' / ',o.name) AS target_label FROM ".$db->prefix().'mjlfinancement_reopening_request r INNER JOIN '.$db->prefix().'mjlfinancement_activity a ON a.entity=r.entity AND a.rowid=r.fk_activity INNER JOIN '.$db->prefix().'mjlfinancement_operation o ON o.entity=r.entity AND o.rowid=r.fk_operation'.$assignment.$where;
	$res=$db->query('SELECT * FROM ('.implode(' UNION ALL ',$queries).') requests ORDER BY date_request DESC,request_type,rowid DESC LIMIT 51 OFFSET '.$offset);if(!$res){mjl_request_unavailable();return;}$rows=array();while($row=$db->fetch_object($res))$rows[]=$row;$hasNext=count($rows)>50;$rows=array_slice($rows,0,50);
	llxHeader('','Demandes d’exception');mjl_navigation_shell_start($user);print '<div class="mjl-workspace">'.mjl_page_header_render('Demandes d’exception',array('description'=>'Annulations et réouvertures liées à une version précise.')).'<section class="mjl-workspace-section">'.mjl_request_feedback().'<form method="GET"><label>Type <select name="type"><option value="">Tous</option><option value="CANCELLATION"'.($type==='CANCELLATION'?' selected':'').'>Annulation</option><option value="REOPENING"'.($type==='REOPENING'?' selected':'').'>Réouverture</option></select></label><label>Statut <select name="status"><option value="">Tous</option>';foreach(array('PENDING'=>'En attente','APPROVED'=>'Approuvée','REJECTED'=>'Rejetée','WITHDRAWN'=>'Retirée')as$value=>$label)print '<option value="'.$value.'"'.($status===$value?' selected':'').'>'.$label.'</option>';print '</select></label><button class="button" type="submit">Filtrer</button></form>';
	if(!$rows)print mjl_ui_system_state('initial-empty','Aucune demande','Aucune demande ne correspond aux filtres.');else foreach($rows as$row)mjl_request_render($row);
	if($page>1||$hasNext){$query=array('type'=>$type,'status'=>$status);print '<nav class="mjl-pagination" aria-label="Pagination des demandes">';if($page>1){if($page-1>1)$query['page']=$page-1;print '<a rel="prev" href="?'.http_build_query($query).'">Précédent</a>';unset($query['page']);}if($hasNext){$query['page']=$page+1;print '<a rel="next" href="?'.http_build_query($query).'">Suivant</a>';}print '</nav>';}
	print '</section></div>';mjl_navigation_shell_end();llxFooter();
}

function mjl_request_feedback(){if(!isset($_GET['result'])||!is_scalar($_GET['result']))return '';$code=(string)$_GET['result'];$map=array('OK'=>array('success','Décision enregistrée','La demande a été mise à jour.'),'STALE_VERSION'=>array('warning','La demande a changé','Rechargez la page.'),'RETRYABLE_CONFLICT'=>array('warning','Conflit temporaire','Une autre action est en cours. Rechargez la page et réessayez.'),'CONFLICT'=>array('warning','Demande devenue obsolète','La cible ou une demande liée a changé.'),'FORBIDDEN'=>array('danger','Action non autorisée','Votre rôle ne permet pas cette action.'),'INVALID_INPUT'=>array('danger','Saisie non valide','Vérifiez le motif et réessayez.'),'FAILED'=>array('danger','Échec','Aucune modification n’a été enregistrée.'));return isset($map[$code])?mjl_ui_system_state($map[$code][0],$map[$code][1],$map[$code][2]):'';}

function mjl_request_post()
{
	global $user;if($_GET||!isset($_SERVER['CONTENT_LENGTH'])||preg_match('/^(0|[1-9][0-9]*)$/',(string)$_SERVER['CONTENT_LENGTH'])!==1||(int)$_SERVER['CONTENT_LENGTH']>16384)mjl_request_bad();if(!isset($_POST['action'])||!is_scalar($_POST['action'])||!isset($_POST['request_type'])||!is_scalar($_POST['request_type']))mjl_request_bad();$action=(string)$_POST['action'];$type=(string)$_POST['request_type'];$allowedActions=array('withdraw','approve','reject');if(!in_array($action,$allowedActions,true)||!in_array($type,array('CANCELLATION','REOPENING'),true))mjl_request_forbidden();$allowed=array('token','mjl_submission','action','request_type','request_id','version');if($action!=='withdraw')$allowed[]='reason';foreach(array_keys($_POST)as$key)if(!is_string($key)||!in_array($key,$allowed,true))mjl_request_forbidden();if(!function_exists('currentToken')||!isset($_POST['token'])||!is_scalar($_POST['token'])||!hash_equals((string)currentToken(),(string)$_POST['token']))mjl_request_forbidden();$id=mjl_request_decimal('request_id',$_POST);$version=mjl_request_decimal('version',$_POST);if($id===''||$version===''||!isset($_POST['mjl_submission'])||!is_scalar($_POST['mjl_submission'])||!mjl_form_submission_consume((string)$_POST['mjl_submission'],mjl_request_context($action,$type,$id,$version)))mjl_request_forbidden();$command=new MjlActivityCommand($GLOBALS['db']);if($action==='withdraw')$result=$type==='CANCELLATION'?$command->withdrawCancellation($id,$version,$user):$command->withdrawReopening($id,$version,$user);else{$reason=isset($_POST['reason'])&&is_scalar($_POST['reason'])?(string)$_POST['reason']:'';$decision=$action==='approve'?'APPROVED':'REJECTED';$result=$type==='CANCELLATION'?$command->decideCancellation($id,$version,$decision,$reason,$user):$command->decideReopening($id,$version,$decision,$reason,$user);}header('Location: '.DOL_URL_ROOT.'/custom/mjlfinancement/operationrequests.php?'.http_build_query(array('result'=>$result['code']??'FAILED')),true,303);exit;
}

function mjl_request_render($row)
{
	global $user;
	$type=(string)$row->request_type;
	$actionUrl=DOL_URL_ROOT.'/custom/mjlfinancement/operationrequests.php';
	$requestedVersion=(int)$row->target_version;$currentVersion=(int)$row->current_target_version;$targetVersionLabel=$currentVersion.($currentVersion!==$requestedVersion?' — cible modifiée':'');
	print '<article class="mjl-operation-card"><h2>'.($type==='CANCELLATION'?'Demande d’annulation':'Demande de réouverture').' — '.dol_escape_htmltag($row->target_label).'</h2><dl class="mjl-activity-meta"><div><dt>Statut</dt><dd>'.dol_escape_htmltag(mjl_request_status_label((string)$row->status)).'</dd></div><div><dt>Version ciblée</dt><dd>'.$requestedVersion.'</dd></div><div><dt>Version actuelle de la cible</dt><dd>'.$targetVersionLabel.'</dd></div><div><dt>Version de la demande</dt><dd>'.(int)$row->version.'</dd></div><div><dt>Demandée par</dt><dd>'.dol_escape_htmltag($row->requester_name_snapshot).'</dd></div></dl><p>'.nl2br(dol_escape_htmltag($row->reason)).'</p>';
	if (isset($row->eligibility) && $row->eligibility['stale']) print '<p><strong>À clôturer</strong> : la cible a changé. La demande peut être rejetée ou retirée par les profils autorisés.</p>';
	if(isset($row->eligibility)?$row->eligibility['withdraw']:($row->status==='PENDING'&&(int)$row->fk_requester===(int)$user->id&&mjl_scope_is_input_agent($user)))print '<form method="POST" action="'.$actionUrl.'">'.mjl_request_hidden('withdraw',$type,$row->rowid,$row->version).'<button class="button button-secondary" type="submit">Retirer la demande</button></form>';
	if($row->status==='PENDING'&&mjl_scope_is_final_validator($user)){foreach(array('approve'=>'Approuver','reject'=>'Rejeter')as$action=>$label) if (!isset($row->eligibility) || $row->eligibility[$action]) print '<form method="POST" action="'.$actionUrl.'">'.mjl_request_hidden($action,$type,$row->rowid,$row->version).'<label>Motif de décision <textarea name="reason" maxlength="2000" required></textarea></label><button class="button'.($action==='reject'?' button-secondary':'').'" type="submit">'.$label.'</button></form>';}
	print '</article>';
}
