CREATE TABLE `llx_mjlfinancement_activity` (
  `rowid` int(11) NOT NULL AUTO_INCREMENT,
  `entity` int(11) NOT NULL DEFAULT 1,
  `ref` varchar(128) NOT NULL,
  `label` varchar(255) NOT NULL,
  `fk_project` int(11) NOT NULL,
  `fk_task` int(11) DEFAULT NULL,
  `date_start` date DEFAULT NULL,
  `date_end` date DEFAULT NULL,
  `note_public` text DEFAULT NULL,
  `note_private` text DEFAULT NULL,
  `date_creation` datetime NOT NULL,
  `tms` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `fk_user_creat` int(11) NOT NULL,
  `fk_user_modif` int(11) DEFAULT NULL,
  `import_key` varchar(14) DEFAULT NULL,
  `status` int(11) NOT NULL DEFAULT 0,
  `fk_user_responsible` int(11) DEFAULT NULL,
  `date_actual_start` date DEFAULT NULL,
  `date_actual_end` date DEFAULT NULL,
  `physical_execution_percent` int(11) DEFAULT NULL,
  `execution_status` varchar(32) DEFAULT NULL,
  `execution_comment` text DEFAULT NULL,
  PRIMARY KEY (`rowid`),
  UNIQUE KEY `uk_mjlfinancement_activity_ref_entity` (`ref`,`entity`),
  KEY `idx_mjlfinancement_activity_entity` (`entity`),
  KEY `idx_mjlfinancement_activity_fk_project` (`fk_project`),
  KEY `idx_mjlfinancement_activity_fk_task` (`fk_task`),
  KEY `idx_mjlfinancement_activity_fk_user_responsible` (`fk_user_responsible`),
  CONSTRAINT `fk_mjlfinancement_activity_project` FOREIGN KEY (`fk_project`) REFERENCES `llx_projet` (`rowid`),
  CONSTRAINT `fk_mjlfinancement_activity_responsible` FOREIGN KEY (`fk_user_responsible`) REFERENCES `llx_user` (`rowid`),
  CONSTRAINT `fk_mjlfinancement_activity_task` FOREIGN KEY (`fk_task`) REFERENCES `llx_projet_task` (`rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
