CREATE TABLE llx_mjlfinancement_reopening_request (
	rowid BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
	entity INT(11) NOT NULL,
	fk_activity INT(11) NOT NULL,
	fk_operation BIGINT(20) NOT NULL,
	fk_target_revision BIGINT(20) NOT NULL,
	target_version BIGINT(20) NOT NULL,
	fk_requester INT(11) NOT NULL,
	requester_name_snapshot VARCHAR(255) NOT NULL,
	requester_role_snapshot VARCHAR(32) NOT NULL,
	reason TEXT NOT NULL,
	status VARCHAR(16) DEFAULT 'PENDING' NOT NULL,
	fk_reviewer INT(11) DEFAULT NULL,
	reviewer_name_snapshot VARCHAR(255) DEFAULT NULL,
	reviewer_role_snapshot VARCHAR(32) DEFAULT NULL,
	decision_reason TEXT DEFAULT NULL,
	date_request DATETIME NOT NULL,
	date_decision DATETIME DEFAULT NULL,
	date_withdrawal DATETIME DEFAULT NULL,
	version BIGINT(20) DEFAULT 1 NOT NULL,
	pending_operation_id BIGINT(20) AS (CASE WHEN status='PENDING' THEN fk_operation ELSE NULL END) PERSISTENT,
	tms TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
	UNIQUE INDEX uk_mjl_reopening_entity_rowid (entity,rowid),
	UNIQUE INDEX uk_mjl_reopening_pending (entity,pending_operation_id),
	INDEX idx_mjl_reopening_activity (entity,fk_activity,status,rowid),
	INDEX idx_mjl_reopening_operation (entity,fk_operation),
	INDEX idx_mjl_reopening_requester (fk_requester),
	INDEX idx_mjl_reopening_reviewer (fk_reviewer),
	CONSTRAINT chk_mjl_reopening_entity CHECK (entity > 0),
	CONSTRAINT chk_mjl_reopening_version CHECK (target_version > 0 AND version > 0),
	CONSTRAINT chk_mjl_reopening_reason CHECK (reason REGEXP '[^[:space:]]'),
	CONSTRAINT chk_mjl_reopening_status CHECK (status IN ('PENDING','APPROVED','REJECTED','WITHDRAWN')),
	CONSTRAINT chk_mjl_reopening_state CHECK ((status='PENDING' AND fk_reviewer IS NULL AND reviewer_name_snapshot IS NULL AND reviewer_role_snapshot IS NULL AND decision_reason IS NULL AND date_decision IS NULL AND date_withdrawal IS NULL) OR (status IN ('APPROVED','REJECTED') AND fk_reviewer IS NOT NULL AND reviewer_name_snapshot IS NOT NULL AND reviewer_name_snapshot REGEXP '[^[:space:]]' AND reviewer_role_snapshot='VALIDATEUR_DEFINITIF' AND decision_reason IS NOT NULL AND decision_reason REGEXP '[^[:space:]]' AND date_decision IS NOT NULL AND date_withdrawal IS NULL) OR (status='WITHDRAWN' AND fk_reviewer IS NULL AND reviewer_name_snapshot IS NULL AND reviewer_role_snapshot IS NULL AND decision_reason IS NULL AND date_decision IS NULL AND date_withdrawal IS NOT NULL))
) ENGINE=innodb DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
