CREATE TABLE llx_mjlfinancement_activity (
	rowid INT(11) AUTO_INCREMENT PRIMARY KEY,
	entity INT(11) NOT NULL,
	ref VARCHAR(128) NOT NULL,
	fk_partner INT(11) NOT NULL,
	fk_project INT(11) NOT NULL,
	name VARCHAR(255) NOT NULL,
	description TEXT NOT NULL,
	date_start DATE NOT NULL,
	date_end DATE NOT NULL,
	draft_authorized_amount BIGINT(20) NOT NULL,
	first_submitted_amount BIGINT(20) DEFAULT NULL,
	latest_validated_amount BIGINT(20) DEFAULT NULL,
	validation_status VARCHAR(40) DEFAULT 'DRAFT' NOT NULL,
	is_cancelled TINYINT(1) DEFAULT 0 NOT NULL,
	version BIGINT(20) DEFAULT 1 NOT NULL,
	date_creation DATETIME NOT NULL,
	tms TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
	fk_user_creat INT(11) NOT NULL,
	fk_user_modif INT(11) DEFAULT NULL,
	fk_user_responsible INT(11) DEFAULT NULL,
	CONSTRAINT chk_mjl_activity_entity_positive CHECK (entity > 0),
	CONSTRAINT chk_mjl_activity_ref_nonblank CHECK (ref REGEXP '[^[:space:]]'),
	CONSTRAINT chk_mjl_activity_name_nonblank CHECK (name REGEXP '[^[:space:]]'),
	CONSTRAINT chk_mjl_activity_description_nonblank CHECK (description REGEXP '[^[:space:]]'),
	CONSTRAINT chk_mjl_activity_dates CHECK (date_end >= date_start),
	CONSTRAINT chk_mjl_activity_draft_amount CHECK (draft_authorized_amount >= 0),
	CONSTRAINT chk_mjl_activity_first_amount CHECK (first_submitted_amount IS NULL OR first_submitted_amount >= 0),
	CONSTRAINT chk_mjl_activity_validated_amount CHECK (latest_validated_amount IS NULL OR latest_validated_amount >= 0),
	CONSTRAINT chk_mjl_activity_validation_status CHECK (validation_status IN ('DRAFT','SUBMITTED','RETURNED_SUPERVISOR','PREVALIDATED','RETURNED_VALIDATOR','FINAL_VALIDATED','CANCELLED')),
	CONSTRAINT chk_mjl_activity_cancelled CHECK (is_cancelled IN (0,1) AND ((is_cancelled = 1 AND validation_status = 'CANCELLED') OR (is_cancelled = 0 AND validation_status <> 'CANCELLED'))),
	CONSTRAINT chk_mjl_activity_version CHECK (version >= 1),
	CONSTRAINT chk_mjl_activity_responsible_dormant CHECK (fk_user_responsible IS NULL),
	CONSTRAINT chk_mjl_activity_rst005_dormant CHECK (validation_status = 'DRAFT' AND is_cancelled = 0 AND first_submitted_amount IS NULL AND latest_validated_amount IS NULL)
) ENGINE=innodb DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
