CREATE TABLE llx_mjlfinancement_review_decision (
	rowid BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
	entity INT(11) NOT NULL,
	fk_activity INT(11) NOT NULL,
	fk_revision BIGINT(20) NOT NULL,
	stage VARCHAR(16) NOT NULL,
	decision_type VARCHAR(32) NOT NULL,
	fk_actor INT(11) NOT NULL,
	actor_name_snapshot VARCHAR(255) NOT NULL,
	actor_role_snapshot VARCHAR(40) NOT NULL,
	reason TEXT DEFAULT NULL,
	requested_amount BIGINT(20) DEFAULT NULL,
	fk_prevalidation_decision BIGINT(20) DEFAULT NULL,
	state_before VARCHAR(40) NOT NULL,
	state_after VARCHAR(40) NOT NULL,
	date_decision DATETIME NOT NULL,
	UNIQUE INDEX uk_mjl_decision_revision_stage (entity,fk_revision,stage),
	INDEX idx_mjl_decision_activity (entity,fk_activity),
	CONSTRAINT chk_mjl_decision_entity CHECK (entity > 0),
	CONSTRAINT chk_mjl_decision_stage CHECK (stage IN ('SUPERVISOR','VALIDATOR')),
	CONSTRAINT chk_mjl_decision_type CHECK (decision_type IN ('PREVALIDATED','RETURNED_SUPERVISOR','FINAL_VALIDATED','RETURNED_VALIDATOR')),
	CONSTRAINT chk_mjl_decision_shape CHECK ((stage='SUPERVISOR' AND decision_type IN ('PREVALIDATED','RETURNED_SUPERVISOR')) OR (stage='VALIDATOR' AND decision_type IN ('FINAL_VALIDATED','RETURNED_VALIDATOR'))),
	CONSTRAINT chk_mjl_decision_reason CHECK ((decision_type IN ('RETURNED_SUPERVISOR','RETURNED_VALIDATOR') AND reason REGEXP '[^[:space:]]') OR (decision_type IN ('PREVALIDATED','FINAL_VALIDATED') AND reason IS NULL)),
	CONSTRAINT chk_mjl_decision_requested CHECK ((decision_type='RETURNED_VALIDATOR' AND (requested_amount IS NULL OR requested_amount > 0)) OR (decision_type<>'RETURNED_VALIDATOR' AND requested_amount IS NULL))
) ENGINE=innodb DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
