CREATE TABLE llx_mjlfinancement_audit_event (
	rowid BIGINT AUTO_INCREMENT PRIMARY KEY,
	entity INTEGER DEFAULT 1 NOT NULL,
	object_type VARCHAR(64) NOT NULL,
	object_id BIGINT DEFAULT NULL,
	object_ref VARCHAR(128) DEFAULT NULL,
	activity_id BIGINT DEFAULT NULL,
	operation_id BIGINT DEFAULT NULL,
	revision_id BIGINT DEFAULT NULL,
	actor_id INTEGER DEFAULT NULL,
	actor_name_snapshot VARCHAR(255) NOT NULL,
	actor_role_snapshot VARCHAR(64) NOT NULL,
	event_date DATETIME NOT NULL,
	action VARCHAR(96) NOT NULL,
	previous_values_json LONGTEXT DEFAULT NULL,
	new_values_json LONGTEXT DEFAULT NULL,
	reason TEXT,
	state_before VARCHAR(64) DEFAULT NULL,
	state_after VARCHAR(64) DEFAULT NULL,
	target_version BIGINT DEFAULT NULL,
	result VARCHAR(16) NOT NULL,
	context_json LONGTEXT DEFAULT NULL,
	date_creation DATETIME NOT NULL,
	CONSTRAINT chk_mjl_audit_result CHECK (result IN ('SUCCESS', 'DENIED', 'FAILED')),
	CONSTRAINT chk_mjl_audit_previous_json CHECK (previous_values_json IS NULL OR JSON_VALID(previous_values_json)),
	CONSTRAINT chk_mjl_audit_new_json CHECK (new_values_json IS NULL OR JSON_VALID(new_values_json)),
	CONSTRAINT chk_mjl_audit_context_json CHECK (context_json IS NULL OR JSON_VALID(context_json))
) ENGINE=innodb;
