CREATE TABLE llx_mjlfinancement_password_reset (
	rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
	entity INTEGER DEFAULT 1 NOT NULL,
	fk_user INTEGER NOT NULL,
	status VARCHAR(32) DEFAULT 'sent' NOT NULL,
	token_hash VARCHAR(128) DEFAULT NULL,
	date_expiry DATETIME NOT NULL,
	date_consumed DATETIME DEFAULT NULL,
	date_creation DATETIME NOT NULL,
	tms TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat INTEGER NOT NULL,
	fk_user_modif INTEGER DEFAULT NULL,
	import_key VARCHAR(14)
) ENGINE=innodb;
