CREATE TABLE llx_mjlfinancement_expense (
	rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
	entity INTEGER DEFAULT 1 NOT NULL,
	ref VARCHAR(128) NOT NULL,
	fk_project INTEGER NOT NULL,
	fk_convention INTEGER NOT NULL,
	fk_mjl_activity INTEGER DEFAULT NULL,
	fk_budget_line INTEGER NOT NULL,
	amount DOUBLE(24,8) NOT NULL,
	prevalidated_amount DOUBLE(24,8) DEFAULT NULL,
	final_validated_amount DOUBLE(24,8) DEFAULT NULL,
	disbursed_amount DOUBLE(24,8) DEFAULT NULL,
	expense_date DATE DEFAULT NULL,
	description TEXT,
	supporting_document VARCHAR(255) DEFAULT NULL,
	fk_user_valid INTEGER DEFAULT NULL,
	fk_user_prevalidated INTEGER DEFAULT NULL,
	fk_user_final_valid INTEGER DEFAULT NULL,
	fk_user_disbursed INTEGER DEFAULT NULL,
	validation_date DATETIME DEFAULT NULL,
	prevalidation_date DATETIME DEFAULT NULL,
	final_validation_date DATETIME DEFAULT NULL,
	disbursement_date DATE DEFAULT NULL,
	beneficiary_name VARCHAR(255) DEFAULT NULL,
	correction_reason TEXT,
	submitted_at DATETIME DEFAULT NULL,
	note_public TEXT,
	note_private TEXT,
	date_creation DATETIME NOT NULL,
	tms TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat INTEGER NOT NULL,
	fk_user_modif INTEGER DEFAULT NULL,
	import_key VARCHAR(14),
	status INTEGER DEFAULT 0 NOT NULL
) ENGINE=innodb;
