CREATE TABLE llx_mjlfinancement_user_role (
	rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
	entity INTEGER DEFAULT 1 NOT NULL,
	fk_user INTEGER NOT NULL,
	role_code VARCHAR(64) NOT NULL,
	is_active TINYINT DEFAULT 1 NOT NULL,
	active_user_id INTEGER AS (CASE WHEN is_active = 1 THEN fk_user ELSE NULL END) PERSISTENT,
	date_start DATETIME DEFAULT NULL,
	date_end DATETIME DEFAULT NULL,
	source VARCHAR(64) DEFAULT NULL,
	note TEXT,
	date_creation DATETIME NOT NULL,
	tms TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat INTEGER DEFAULT NULL,
	fk_user_modif INTEGER DEFAULT NULL,
	import_key VARCHAR(14)
) ENGINE=innodb;
