CREATE TABLE llx_mjlfinancement_expense (
	rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
	entity INTEGER DEFAULT 1 NOT NULL,
	ref VARCHAR(128) NOT NULL,
	label VARCHAR(255),
	fk_budget_line INTEGER NOT NULL,
	fk_expensereport INTEGER DEFAULT NULL,
	amount DOUBLE(24,8) NOT NULL,
	expense_date DATE DEFAULT NULL,
	note_public TEXT,
	note_private TEXT,
	date_creation DATETIME NOT NULL,
	tms TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat INTEGER NOT NULL,
	fk_user_modif INTEGER DEFAULT NULL,
	import_key VARCHAR(14),
	status INTEGER DEFAULT 0 NOT NULL
) ENGINE=innodb;
