CREATE TABLE llx_mjlfinancement_budget_line (
	rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
	entity INTEGER DEFAULT 1 NOT NULL,
	ref VARCHAR(128) NOT NULL,
	label VARCHAR(255),
	fk_project INTEGER DEFAULT NULL,
	fk_convention INTEGER NOT NULL,
	fk_mjl_activity INTEGER DEFAULT NULL,
	fk_activity INTEGER DEFAULT NULL,
	initial_budget DOUBLE(24,8) DEFAULT NULL,
	revised_budget DOUBLE(24,8) DEFAULT NULL,
	committed_amount DOUBLE(24,8) DEFAULT 0,
	spent_amount DOUBLE(24,8) DEFAULT 0,
	remaining_amount DOUBLE(24,8) DEFAULT 0,
	category VARCHAR(64) DEFAULT NULL,
	note_public TEXT,
	note_private TEXT,
	date_creation DATETIME NOT NULL,
	tms TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat INTEGER NOT NULL,
	fk_user_modif INTEGER DEFAULT NULL,
	import_key VARCHAR(14),
	status INTEGER DEFAULT 0 NOT NULL
) ENGINE=innodb;
