CREATE TABLE llx_mjlfinancement_invitation (
	rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
	entity INTEGER DEFAULT 1 NOT NULL,
	fk_user INTEGER NOT NULL,
	role_code VARCHAR(64) NOT NULL,
	status VARCHAR(32) NOT NULL,
	token_selector VARCHAR(64) NOT NULL,
	token_hash CHAR(64) DEFAULT NULL,
	live_user_id INTEGER AS (CASE WHEN status IN ('pending_send', 'sent') THEN fk_user ELSE NULL END) PERSISTENT,
	date_expiry DATETIME NOT NULL,
	date_sent DATETIME DEFAULT NULL,
	date_accepted DATETIME DEFAULT NULL,
	date_revoked DATETIME DEFAULT NULL,
	fk_user_sender INTEGER NOT NULL,
	fk_user_revoked INTEGER DEFAULT NULL,
	date_creation DATETIME NOT NULL,
	tms TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat INTEGER NOT NULL,
	fk_user_modif INTEGER DEFAULT NULL,
	CONSTRAINT chk_mjl_invitation_role CHECK (role_code IN ('AGENT_SAISIE', 'AGENT_VERIFICATEUR', 'VALIDATEUR_DEFINITIF')),
	CONSTRAINT chk_mjl_invitation_status CHECK (status IN ('pending_send', 'sent', 'accepted', 'revoked', 'send_failed')),
	CONSTRAINT chk_mjl_invitation_credential_state CHECK ((status IN ('pending_send', 'sent') AND token_hash IS NOT NULL) OR (status IN ('accepted', 'revoked', 'send_failed') AND token_hash IS NULL)),
	CONSTRAINT chk_mjl_invitation_terminal_date CHECK ((status IN ('pending_send', 'sent') AND date_accepted IS NULL AND date_revoked IS NULL) OR (status = 'accepted' AND date_accepted IS NOT NULL) OR (status IN ('revoked', 'send_failed') AND date_revoked IS NOT NULL))
) ENGINE=innodb;
