CREATE TABLE llx_mjlfinancement_exchange_log (
	rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
	entity INTEGER DEFAULT 1 NOT NULL,
	ref VARCHAR(128) NOT NULL,
	object_type VARCHAR(64) NOT NULL,
	object_id INTEGER NOT NULL,
	exchange_date DATETIME NOT NULL,
	actor INTEGER NOT NULL,
	actor_role VARCHAR(64) NOT NULL,
	channel VARCHAR(64) DEFAULT NULL,
	subject VARCHAR(255) DEFAULT NULL,
	message TEXT NOT NULL,
	date_creation DATETIME NOT NULL,
	tms TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat INTEGER NOT NULL,
	fk_user_modif INTEGER DEFAULT NULL,
	import_key VARCHAR(14)
) ENGINE=innodb;
