CREATE TABLE llx_mjlfinancement_invitation (
	rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
	entity INTEGER DEFAULT 1 NOT NULL,
	fk_user INTEGER NOT NULL,
	status VARCHAR(32) NOT NULL,
	token_hash VARCHAR(128) DEFAULT NULL,
	date_expiry DATETIME DEFAULT NULL,
	date_sent DATETIME DEFAULT NULL,
	date_accepted DATETIME DEFAULT NULL,
	date_revoked DATETIME DEFAULT NULL,
	fk_user_sender INTEGER DEFAULT NULL,
	fk_user_revoked INTEGER DEFAULT NULL,
	date_creation DATETIME NOT NULL,
	tms TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat INTEGER NOT NULL,
	fk_user_modif INTEGER DEFAULT NULL,
	import_key VARCHAR(14)
) ENGINE=innodb;
