CREATE TABLE llx_mjlfinancement_access_audit (
	rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
	entity INTEGER DEFAULT 1 NOT NULL,
	fk_user INTEGER DEFAULT NULL,
	fk_actor INTEGER DEFAULT NULL,
	event VARCHAR(64) NOT NULL,
	event_date DATETIME NOT NULL,
	context TEXT,
	date_creation DATETIME NOT NULL,
	tms TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat INTEGER DEFAULT NULL,
	fk_user_modif INTEGER DEFAULT NULL,
	import_key VARCHAR(14)
) ENGINE=innodb;
