CREATE TABLE llx_mjlfinancement_export_record (
 rowid BIGINT AUTO_INCREMENT PRIMARY KEY,
 entity INT NOT NULL,
 ref VARCHAR(64) NOT NULL,
 report_type VARCHAR(24) NOT NULL,
 projection_version INT NOT NULL,
 format VARCHAR(8) NOT NULL,
 status VARCHAR(16) NOT NULL DEFAULT 'GENERATED',
 fk_generator INT NOT NULL,
 generator_name_snapshot VARCHAR(255) NOT NULL,
 generator_role_snapshot VARCHAR(32) NOT NULL,
 date_snapshot DATETIME NOT NULL,
 date_generation DATETIME NOT NULL,
 filters_json TEXT NOT NULL,
 scope_json LONGTEXT NOT NULL,
 body_row_count INT NOT NULL,
 byte_count INT NOT NULL,
 content_sha256 CHAR(64) NOT NULL,
 fk_audit_event BIGINT NOT NULL,
 UNIQUE KEY uk_mjl_report_ref (entity,ref),
 UNIQUE KEY uk_mjl_report_audit (fk_audit_event),
 KEY idx_mjl_report_date (entity,date_generation,rowid),
 CONSTRAINT fk_mjl_report_audit FOREIGN KEY (fk_audit_event) REFERENCES llx_mjlfinancement_audit_event(rowid) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT chk_mjl_report_entity CHECK (entity > 0),
 CONSTRAINT chk_mjl_report_projection CHECK (projection_version=1),
 CONSTRAINT chk_mjl_report_type CHECK (report_type IN ('activities','operations','activity_detail','portfolio','audit')),
 CONSTRAINT chk_mjl_report_format CHECK (format IN ('pdf','xlsx','csv')),
 CONSTRAINT chk_mjl_report_status CHECK (status='GENERATED'),
 CONSTRAINT chk_mjl_report_generator CHECK (fk_generator > 0 AND generator_role_snapshot IN ('AGENT_SAISIE','AGENT_VERIFICATEUR','VALIDATEUR_DEFINITIF','ADMIN_PLATEFORME') AND (generator_role_snapshot <> 'ADMIN_PLATEFORME' OR report_type='audit')),
 CONSTRAINT chk_mjl_report_filters CHECK (JSON_VALID(filters_json)),
 CONSTRAINT chk_mjl_report_scope CHECK (JSON_VALID(scope_json)),
 CONSTRAINT chk_mjl_report_size CHECK (body_row_count >= 0 AND body_row_count <= 10000 AND (format <> 'pdf' OR body_row_count <= 500) AND byte_count > 0 AND byte_count <= 20971520),
 CONSTRAINT chk_mjl_report_hash CHECK (content_sha256 REGEXP '^[0-9a-f]{64}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
