CREATE TABLE llx_mjlfinancement_operation (
	rowid BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
	entity INT(11) NOT NULL,
	fk_activity INT(11) NOT NULL,
	fk_operation_type INT(11) NOT NULL,
	name VARCHAR(255) NOT NULL,
	authorized_amount BIGINT(20) NOT NULL,
	status VARCHAR(16) DEFAULT 'TODO' NOT NULL,
	spent_amount BIGINT(20) DEFAULT NULL,
	observation TEXT DEFAULT NULL,
	version BIGINT(20) DEFAULT 1 NOT NULL,
	date_removed DATETIME DEFAULT NULL,
	fk_user_removed INT(11) DEFAULT NULL,
	date_creation DATETIME NOT NULL,
	tms TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
	fk_user_creat INT(11) NOT NULL,
	fk_user_modif INT(11) DEFAULT NULL,
	UNIQUE INDEX uk_mjl_operation_entity_rowid (entity,rowid),
	INDEX idx_mjl_operation_activity (entity,fk_activity,date_removed),
	INDEX idx_mjl_operation_type (entity,fk_operation_type),
	CONSTRAINT chk_mjl_operation_entity CHECK (entity > 0),
	CONSTRAINT chk_mjl_operation_name CHECK (name REGEXP '[^[:space:]]'),
	CONSTRAINT chk_mjl_operation_amount CHECK (authorized_amount > 0),
	CONSTRAINT chk_mjl_operation_version CHECK (version > 0),
	CONSTRAINT chk_mjl_operation_phase2 CHECK (status='TODO' AND spent_amount IS NULL AND observation IS NULL),
	CONSTRAINT chk_mjl_operation_removal CHECK ((date_removed IS NULL AND fk_user_removed IS NULL) OR (date_removed IS NOT NULL AND fk_user_removed IS NOT NULL))
) ENGINE=innodb DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
