const test=require('node:test');const assert=require('node:assert/strict');const {execFileSync}=require('node:child_process');const path=require('node:path');
const lib=path.resolve(__dirname,'../../custom/mjlfinancement/lib/mjl_audit_projection.lib.php');
function project(event){const input=Buffer.from(JSON.stringify(event)).toString('base64');return JSON.parse(execFileSync('php',['-r',`require '${lib}';echo json_encode(mjl_audit_project_event(json_decode(base64_decode('${input}'),true)));`],{encoding:'utf8'}));}
const base={rowid:'7',entity:1,object_type:'activity',object_ref:'ACT-7',actor_name_snapshot:'Nom historique',actor_role_snapshot:'VALIDATEUR_DEFINITIF',event_date:'2026-09-09 12:00:00',action:'ACTIVITY_CREATED',result:'SUCCESS',context_json:JSON.stringify({reference:'ACT-7'})};
test('audit projection preserves historical metadata and explicit context paths',()=>{const r=project(base);assert.equal(r[0].event_id,'7');assert.equal(r[0].actor_name,'Nom historique');assert.equal(r[0].path,'context.reference');assert.equal(r[0].after,'ACT-7');assert.equal(r[0].before_type,'Non enregistré');});
test('audit reference changes use nested before/after without inventing deletion',()=>{const r=project({...base,action:'field_changed',object_type:'mjlfinancement_project',context_json:JSON.stringify({legacy_ref_prefix:'WFA-RST003',import_key:null}),new_values_json:JSON.stringify({label:{before:'Ancien',after:'Nouveau'}})});const c=r.find(x=>x.path==='label');assert.equal(c.before,'Ancien');assert.equal(c.after,'Nouveau');});
test('audit redacts a whole value before continuation boundaries and preserves numbered parts',()=>{const text='é'.repeat(3994)+' token=private-value-to-hide '+'suite'.repeat(1000);const r=project({...base,reason:text});const chunks=r.filter(x=>x.path==='reason');assert.ok(chunks.length>1);assert.equal(chunks[0].part,1);assert.equal(chunks[0].parts,chunks.length);assert.ok(chunks.map(x=>x.after).join('').includes('[REDACTED]'));assert.ok(!JSON.stringify(r).includes('private-value-to-hide'));});
test('audit refuses unknown actions, unknown fields and malformed shapes',()=>{for(const event of [{...base,action:'FUTURE_ACTION'},{...base,context_json:'{"unknown":"value"}'},{...base,context_json:'{"reference":{}}'},{...base,context_json:'null'}])assert.throws(()=>project(event));});
test('quoted credentials with spaces and escapes are redacted in reason, payload and metadata before splitting',()=>{const secret='private quoted \\" credential';const text='x'.repeat(3990)+JSON.stringify({password:secret})+' end';const r=project({...base,reason:text,actor_name_snapshot:JSON.stringify({token:'secret with spaces'}),context_json:JSON.stringify({reference:text})});assert.ok(!JSON.stringify(r).includes('private quoted'));assert.ok(!JSON.stringify(r).includes('secret with spaces'));assert.ok(!JSON.stringify(r).includes('credential'));assert.ok(r.some(x=>x.after.includes('[REDACTED]')));});
test('automatic status causes receive explicit French labels while raw causes remain recorded',()=>{const r=project({...base,action:'ACTIVITY_EXECUTION_STATUS_CHANGED',previous_values_json:'{"execution_status":"NOT_STARTED"}',new_values_json:'{"execution_status":"UPCOMING"}',context_json:'{"source":"SCHEDULED"}'});assert.match(r[0].action_label,/automatiquement.*planifié/);assert.equal(r.find(x=>x.path==='context.source').after,'SCHEDULED');});
