const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {spawnSync}=require('node:child_process');
const script=path.resolve(__dirname,'../../custom/mjlfinancement/scripts/rst006b_fast_cutover.js');
const { validateEmptyEvidence }=require(script);

const emptyEvidence=()=>({admin:{rowid:1,entity:0,login:'admin',active:true},zero_row_invariants:{non_admin_users:0,partners:0,projects:0,mjl_business_rows:0,ecm_files:0}});

test('RST-006B fast cutover documents the approved guarded sequence',()=>{const result=spawnSync(process.execPath,[script,'--help'],{encoding:'utf8'});assert.equal(result.status,0);assert.match(result.stdout,/stop.*private backup.*migrate.*verify.*cron.*restart.*health/is);});
test('RST-006B fast cutover rejects an inexact confirmation before Docker',()=>{const result=spawnSync(process.execPath,[script,'--confirm=wrong'],{encoding:'utf8'});assert.equal(result.status,2);assert.equal(result.stderr,'Use --confirm=RST-006B-FAST or --help.\n');});
test('RST-006B cutover binds committed source and keeps traffic stopped through acceptance',()=>{const source=fs.readFileSync(script,'utf8');assert.match(source,/status', '--porcelain/);assert.match(source,/rst006b-before-/);assert.match(source,/fs\.fsyncSync\(descriptor\)/);assert.match(source,/sha256sum/);assert.match(source,/MjlExecutionReconciler/);assert.match(source,/activity_execution_schema\.php/);assert.match(source,/mjl-rst006b-cutover-capability/);assert.doesNotMatch(source,/rollback/);const stop=source.indexOf("dc(['stop', 'dolibarr']");const preflight=source.indexOf('emptyEvidence();',stop);const apply=source.indexOf("migration('apply')",preflight);const bootstrap=source.indexOf('bootstrap_poc.php',apply);const verify=source.indexOf('activity_execution_schema.php',bootstrap);const postflight=source.indexOf('emptyEvidence();',verify);const start=source.indexOf("dc(['start', 'dolibarr']",postflight);assert.ok(stop<preflight&&preflight<apply&&apply<bootstrap&&bootstrap<verify&&verify<postflight&&postflight<start);const catchAt=source.indexOf('} catch (error) {');const catchBlock=source.slice(catchAt,source.indexOf('} finally {',catchAt));assert.match(catchBlock,/verify-predecessor/);assert.doesNotMatch(catchBlock,/migration\('verify'\)/);});

test('RST-006B empty evidence rejects missing or contaminated shared invariants',()=>{assert.deepEqual(validateEmptyEvidence(emptyEvidence()),emptyEvidence());for(const mutate of [(value)=>{value.admin=null;},(value)=>{value.admin.active=false;},(value)=>{value.zero_row_invariants.partners=1;},(value)=>{delete value.zero_row_invariants.ecm_files;}]){const value=emptyEvidence();mutate(value);assert.throws(()=>validateEmptyEvidence(value));}});
test('RST-006B ephemeral setup is covered by cleanup even on early failure',()=>{const source=fs.readFileSync(script,'utf8');const tryAt=source.indexOf('  try {',source.indexOf('function execute()'));const capabilityAt=source.indexOf('fs.writeFileSync(capabilityFile',tryAt);const serviceAt=source.indexOf('services()',capabilityAt);const configAt=source.indexOf("dc(['cp'",serviceAt);const finallyAt=source.indexOf('} finally {',configAt);const unlinkConfig=source.indexOf('fs.unlinkSync(configFile)',finallyAt);const unlinkCapability=source.indexOf('fs.unlinkSync(capabilityFile)',finallyAt);assert.ok(tryAt<capabilityAt&&capabilityAt<serviceAt&&serviceAt<configAt&&configAt<finallyAt&&finallyAt<unlinkConfig&&finallyAt<unlinkCapability);});
test('RST-006B recovery owns only a target start and removes unverified backups',()=>{const source=fs.readFileSync(script,'utf8');const startAttempt=source.indexOf('targetStartAttempted = true');const start=source.indexOf("dc(['start', 'dolibarr']",startAttempt);const catchAt=source.indexOf('} catch (error) {',start);const ownershipGate=source.indexOf('if (targetStartAttempted)',catchAt);const recoveryStop=source.indexOf("dc(['stop', 'dolibarr']",ownershipGate);const finallyAt=source.indexOf('} finally {',recoveryStop);const unverifiedCleanup=source.indexOf("backup !== '' && backupSha256 === ''",finallyAt);assert.ok(startAttempt<start&&start<catchAt&&catchAt<ownershipGate&&ownershipGate<recoveryStop&&recoveryStop<finallyAt&&finallyAt<unverifiedCleanup);});
